# Generated by Django 5.2.3 on 2025-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1)),
            ],
        ),
    ]
